# syntax=docker/dockerfile:1

FROM python:3.8

WORKDIR ./app

COPY ./app/requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8501

COPY ./app ./

ENTRYPOINT ["streamlit", "run"]

CMD ["main.py"]